Takuzu: main.o affichage.o fonctions.o test.o
	gcc -o Takuzu main.o affichage.o fonctions.o test.o

main.o: main.c
	gcc -c main.c

affichage.o: affichage.c
	gcc -c affichage.c

fonctions.o: fonctions.c
	gcc -c fonctions.c

test.o: test.c
	gcc -c test.c
